baseURL = 'https://merallunaur.com/'
languageCode = 'en-us'
title = 'The Conjecture of a Crocodile'
theme = 'PaperMod'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = false

[languages]
  [languages.en]
    languageName = "English"
    weight = 1